### ISSUE TITLE
Tunes data not wihtin block['data'] but within block['tunes']

### ISSUE THREAD

**Issue by mauritskorse** [codex-team/codex.editor.backend#67]
PR https://github.com/editor-js/editorjs-php/pull/59 assumes that the tunes data is within the block['data'] object, however editor.js outputs the tunes data not to block['data'] but to block['tunes']
```js
      const output = {
        id,
        type: tool,
        data,
        ...!_.isEmpty(tunes) && {
          tunes,
        },
      };
      blocks.push(output);
```
https://github.com/codex-team/editor.js/blob/1320b047a20afe7ab6cf0e63b4125616ec6dc06b/src/components/modules/saver.ts#L89-L98

**Comment by neSpecc** [comment]
Hey. I'm not sure I've understood the problem. On your code example, `tunes` are not included at the `data`.

**Comment by mauritskorse** [comment]
Never mind, it seems composer did not install the latest version. All working now.
